prep-html-syntax - Jae Song
jaegunsong/prep-0222-code-solutions pull request #3
Opened 2022-02-19 22:23 UTC by jaegunsong

![yodass](https://user-images.githubusercontent.com/99282675/154821048-8526d1f5-27d2-41bb-ba90-aaa2a02d0f06.png)

2022-02-20 17:36 UTC, thebearingedge requested changes

2022-02-20 17:36 UTC, thebearingedge commented on prep-html-syntax/index.html
> +<html>
Hi Jae, be sure to include a `<head></head>` element before your `<body></body>` element.

2022-02-22 23:07 UTC, jaegunsong commented
![yodass](https://user-images.githubusercontent.com/99282675/155234739-ac73f039-839b-4467-ab26-a98797e90c43.png)

2022-02-23 01:04 UTC, thebearingedge approved these changes

2022-02-23 02:29 UTC, merged